### ISSUE TITLE
Fix Hashing

### ISSUE THREAD

**Issue by muriloaj** [guilhermebotossi/upmexmples#1]
Just make make it compilable:

package zzzzzzzzzzzzzzzzzzz;
import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

public class Hashing {
    
    public static String md5Hashing(String str) throws Exception {
        MessageDigest instance = getDigest("MD5");
        byte[] digest = digest(instance, str);
        
        return toHexHash(digest);
    }
    
    public static String sha256Hashing(String str) throws Exception {
        MessageDigest instance = getDigest("SHA-256");
        byte[] digest = digest(instance, str);
        
        return toHexHash(digest);
    }
    
    public static String sha512Hashing(String str) throws Exception {
        MessageDigest instance = getDigest("SHA-512");
        byte[] digest = digest(instance, str);
        
        return toHexHash(digest);
    }
    
    public static String md5HashingWithSalt(String str, String salt) throws Exception {
        MessageDigest instance = getDigest("MD5");
        byte[] digest = digestWithSalt(instance, str, salt);
        
        return toHexHash(digest);
    }
    
    public static String sha256HashingWithSalt(String str, String salt) throws Exception {
        MessageDigest instance = getDigest("SHA-256");
        byte[] digest = digestWithSalt(instance, str, salt);
        
        return toHexHash(digest);
    }
    
    public static String sha512HashingWithSalt(String str, String salt) throws Exception {
        MessageDigest instance = getDigest("SHA-512");
        byte[] digest = digestWithSalt(instance, str, salt);
        
        return toHexHash(digest);
    }
    
    public static String hashOverHash(String algoritmo, int numberOfIterations) {
		return algoritmo;
    }

    public static String hashOverHashWithSalt(String algoritmo, int numberOfIterations) {
		return algoritmo;
        
    }

    private static MessageDigest getDigest(String algoritmo) throws NoSuchAlgorithmException {
        return MessageDigest.getInstance(algoritmo.toUpperCase());
    }
    
    private static String toHexHash(byte[] hash) {
        return String.format("%x", new BigInteger(1, hash));
    }
    
    private static MessageDigest addSalt(MessageDigest digest, String salt) throws UnsupportedEncodingException {
        digest.update(salt.getBytes(CHARSET));
        return digest;
    }
    
    private static byte[] digest(MessageDigest digest, String str) throws UnsupportedEncodingException {
        return digest.digest(str.getBytes(CHARSET));
    }

    private static byte[] digestWithSalt(MessageDigest digest, String str, String salt) throws UnsupportedEncodingException {
        Hashing.addSalt(digest, salt);
        return digest.digest(str.getBytes(CHARSET));
    }
    
    
    public static void main(String[] args) throws Exception {
        String plainText = "TESTE";
        
        System.out.println("Plain Text = " + plainText);
        System.out.println("MD5 = " + Hashing.md5Hashing(plainText));
        System.out.println("SHA-256 = " + Hashing.sha256Hashing(plainText));
        System.out.println("SHA-512 = " + Hashing.sha512Hashing(plainText));

        String salt = "SaltTest";

        System.out.println("MD5 with Salt = " + Hashing.md5HashingWithSalt(plainText, salt));
        System.out.println("SHA-256 with Salt = " + Hashing.sha256HashingWithSalt(plainText, salt));
        System.out.println("SHA-512 with Salt = " + Hashing.sha512HashingWithSalt(plainText, salt));
    }
    
    private static final String CHARSET = "UTF-8";

}

**Comment by guilhermebotossi** [comment]
Done
